DB:
  host: localhost
  username: root
  password: root
  port: 3306
  database: movie

DataBase:
  table:
    - movie
    - music
    - novel

HuLuWa: ['song', 'qing', 'hui', 'bo', 'lin', 'tao', 'chao']
